"""phase9: add REJECTED status and invoice rejection fields

Revision ID: 6548ec09f75e
Revises: 66491177a625
Create Date: 2026-08-30 10:15:48.490992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6548ec09f75e'
down_revision: Union[str, None] = '66491177a625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT auto-generated: Alembic's autogenerate does not detect Postgres
    # ENUM value additions (same limitation encountered in the Phase 5
    # migration for TEXT_EXTRACTED). Added manually, matching that pattern.
    op.execute("ALTER TYPE document_status ADD VALUE IF NOT EXISTS 'REJECTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('rejected_by_user_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # Given an explicit name (autogenerate left this anonymous) so
    # downgrade() can actually reference and drop it — this project's
    # metadata has no naming_convention configured, so an unnamed
    # drop_constraint(None, ...) would fail at runtime.
    op.create_foreign_key(
        'fk_invoices_rejected_by_user_id_users',
        'invoices', 'users', ['rejected_by_user_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoices_rejected_by_user_id_users', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'rejection_reason')
    op.drop_column('invoices', 'rejected_by_user_id')
    op.drop_column('invoices', 'rejected_at')
    # ### end Alembic commands ###

    # NOT auto-generated, and NOT reversible: Postgres does not support
    # removing a value from an existing ENUM type. The REJECTED value added
    # in upgrade() intentionally remains in the document_status type after
    # downgrade — inert or a no-op on the resulting re-upgrade, matching the
    # exact same documented limitation as the Phase 5 migration.
