"""phase5: add extracted_text_storage_key column

Revision ID: 66491177a625
Revises: 665eeeb80973
Create Date: 2026-08-23 11:01:39.857101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66491177a625'
down_revision: Union[str, None] = '665eeeb80973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Not auto-detected by Alembic autogenerate: adding a new value to an
    # existing Postgres ENUM type requires raw DDL. Safe to run inside this
    # migration's transaction (Postgres 12+) as long as the new value isn't
    # *used* within the same transaction — it isn't here.
    op.execute("ALTER TYPE document_status ADD VALUE IF NOT EXISTS 'TEXT_EXTRACTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text_storage_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text_storage_key')
    # ### end Alembic commands ###

    # NOTE: PostgreSQL does not support removing a value from an existing
    # ENUM type (no `ALTER TYPE ... DROP VALUE`). Removing 'TEXT_EXTRACTED'
    # would require rebuilding the enum type (create new type, migrate the
    # column, drop old type) — high-risk DDL for a downgrade path. Left as a
    # documented, accepted limitation: downgrading this migration removes
    # the column but leaves the enum value in place. This is safe (an unused
    # extra enum value is inert) but is not a full schema reversal.
